host: stage.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: fc31
    operating_system:
      name: fedora
      version: "31"
    python_version: "3.7"
    recommendation_type: LATEST
