---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: thamos-advise
  annotations:
    thoth-station.ninja/template-version: 0.1.0-dev
  labels:
    app: thoth
    component: thamos-advise
spec:
  templates:
    - name: thamos-advise
      inputs:
        parameters:
          - name: "GITHUB_EVENT_TYPE"
          - name: "GITHUB_CHECK_RUN_ID"
          - name: "GITHUB_INSTALLATION_ID"
          - name: "BASE_REPO_URL"
          - name: "HEAD_REPO_URL"
          - name: "REVISION"
          - name: "THOTH_HOST"
        artifacts:
          - name: repository
            path: /mnt/inputs/artifacts/repository
            git:
              repo: "{{inputs.parameters.HEAD_REPO_URL}}"
              revision: "{{inputs.parameters.REVISION}}"
      script:
        command:
          - python3
        name: thamos-advise
        image: "quay.io/thoth-station/thamos:v0.8.0-dev"
        source: |
          import os
          import json
          from pathlib import Path

          from thoth.common import init_logging

          from thamos.lib import advise_here
          from thamos.config import config

          init_logging()

          os.chdir("/mnt/inputs/artifacts/repository")

          config.explicit_host = "{{inputs.parameters.THOTH_HOST}}"
          config.tls_verify = True

          analysis_id = advise_here(
            recommendation_type="STABLE",
            nowait=True,
            github_event_type="{{inputs.parameters.GITHUB_EVENT_TYPE}}",
            github_check_run_id="{{inputs.parameters.GITHUB_CHECK_RUN_ID}}",
            github_installation_id="{{inputs.parameters.GITHUB_INSTALLATION_ID}}",
            base_repo_url="{{inputs.parameters.BASE_REPO_URL}}"
          )
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
