apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ultrahook-template
metadata:
  annotations:
    description: Application template to build the ultrahook sidecar container
    tags: ultrahook,webhook,sidecar
    version: 0.1.0-dev
  name: ultrahook-template
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ultrahook
      labels:
        app: qeb-hwt
        component: ultrahook
      annotations:
        thoth-station.ninja/template-version: 0.1.0-dev
    data:
      ULTRAHOOK_API_KEY: "${ULTRAHOOK_API_KEY}"
      ULTRAHOOK_SUBDOMAIN: "${ULTRAHOOK_SUBDOMAIN}"
      ULTRAHOOK_TARGET_HOST: "${ULTRAHOOK_TARGET_HOST}"
      ULTRAHOOK_TARGET_PORT: "${ULTRAHOOK_TARGET_PORT}"

parameters:
  - description: Ultrahook API key
    name: ULTRAHOOK_API_KEY
    required: true
  - description: Ultrahook subdomain
    name: ULTRAHOOK_SUBDOMAIN
    required: true
  - description: Ultrahook host
    name: ULTRAHOOK_TARGET_HOST
    value: localhost
  - description: Ultrahook port
    name: ULTRAHOOK_TARGET_PORT
    value: "8080"
