apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: qeb-hwt-imagestream
  annotations:
    description: "This is the ImageStream for Thoth Service: thamos advise"
    openshift.io/display-name: "Thoth Service: thamos advise"
    version: 0.1.0-dev
    tags: thoth,github,app,thamos
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Qeb-Hwt, the backend
      componets of https://github.com/marketplace/qeb-hwt
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: qeb-hwt-imagestream
    app: qeb-hwt

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: qeb-hwt-webhook-recevier
      annotations:
        thoth-station.ninja/template-version: 0.1.0-dev
      labels:
        app: qeb-hwt
        component: webhook-recevier

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ultrahook
      annotations:
        thoth-station.ninja/template-version: 0.1.0-dev
      labels:
        app: qeb-hwt
        component: ultrahook
